# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
    # Built-in hooks from pre-commit.
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: no-commit-to-branch
        args: [--branch, main, --branch, master]
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
      - id: detect-private-key
        # Checks whether your Python files contain valid Python syntax by parsing them into an AST (Abstract Syntax Tree).
      - id: check-ast
        # Checks for accidental debugging statements left in your code.
      - id: debug-statements

    # To block secret-containing commits
  - repo: https://github.com/gitleaks/gitleaks
    rev: v8.24.2
    hooks:
      - id: gitleaks

  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.16.7
    hooks:
      # Run the linter.
      - id: ruff-check
      # Run the formatter.
      - id: ruff-format
